"""Reconstruct one image from an existing phase hologram."""

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from Optics import Optics
from Trainer import Trainer


def resolve_repo_path(path):
    path = Path(path)
    return path if path.is_absolute() else REPO_ROOT / path


def reconstruct_single(
    rgb_path,
    depth_path,
    hologram_path,
    output_path,
    first_z,
    delta_z,
    channel,
    layer_num,
    LCoS_pitch=3.6e-6,
    LCoS_res_h=2160,
    LCoS_res_w=3840,
    phase_grating=True,
):
    """Run numerical reconstruction for one existing 8-bit phase hologram."""
    for label, path in {
        "RGB image": rgb_path,
        "depth map": depth_path,
        "phase hologram": hologram_path,
    }.items():
        if not os.path.exists(path):
            raise FileNotFoundError(f"{label} not found: {path}")

    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    eval_optics = Optics(
        channel=channel,
        first_z=first_z,
        delta_z=delta_z,
        layer_num=layer_num,
        LCoS_res_h=LCoS_res_h,
        LCoS_res_w=LCoS_res_w,
        LCoS_pitch=LCoS_pitch,
    )
    trainer = Trainer(
        train_optics_ins=None,
        eval_optics_ins=eval_optics,
        phs_code_model=None,
        root_path=os.path.dirname(hologram_path),
    )

    print(f"Reconstructing {hologram_path}")
    trainer.phs_predict(
        rgb_path=rgb_path,
        depth_path=depth_path,
        phs_path=hologram_path,
        img_rec_path=output_path,
        phase_grating=phase_grating,
    )
    print(f"Saved reconstruction: {output_path}")


if __name__ == "__main__":
    # Example: reconstruct the green channel of the demo hologram generated by
    # `python predict.py` (pred/StructurePropagation/image_G_hologram.png).
    RGB_PATH = resolve_repo_path("data/example_input/image.png")
    DEPTH_PATH = resolve_repo_path("data/example_input/image_depth.png")
    HOLOGRAM_PATH = resolve_repo_path("pred/StructurePropagation/image_G_hologram.png")
    OUTPUT_PATH = resolve_repo_path("outputs/single_reconstruction.png")

    reconstruct_single(
        rgb_path=str(RGB_PATH),
        depth_path=str(DEPTH_PATH),
        hologram_path=str(HOLOGRAM_PATH),
        output_path=str(OUTPUT_PATH),
        first_z=0.005,
        delta_z=0.005,
        channel=1,
        layer_num=4,
        phase_grating=True,
    )
